/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */
/*===========   INCLUDE LIB   ===========*/
#include  "STD_TYPES.h"
#include  "BIT_MATH.h"
#include "Delay_interface.h"

/*======================================*/
/*===========  INCLUDE MCAL  ===========*/
#include "TIMER2_Interface.h"
/*======================================*/
/*===========  INCLUDE HAL   ===========*/
#include"servo.h"

void ON_PWM_Door(void)
{

}

void OFF_PWM_Door(void)
{

}

// set needed angel //used
void Servo_angle_Door(u8 Copy_Angle)
{	
	switch (Copy_Angle)
	{
	case 0 :
		M_TIMER_void_TIMER3_DUTYCYCLE(500);	// angle 0  -90
		break;
	case 90 :
		M_TIMER_void_TIMER3_DUTYCYCLE(750);	// angle 90 //0
		break;
	case 180 :
		M_TIMER_void_TIMER3_DUTYCYCLE(1000);	// angle 180  +90
		break;
	}
}
//////////////////////////////////////////////////////////////////////////////////////////////////////

void ON_PWM_Trunk(void)
{

}

void OFF_PWM_Trunk(void)
{

}

// set needed angel // used
void Servo_angle_Trunk(u8 Copy_Angle)
{	
	switch (Copy_Angle)
	{
	case 0 :
		M_TIMER_void_TIMER4_DUTYCYCLE(500);	// angle 0  -90
		break;
	case 90 :
		M_TIMER_void_TIMER4_DUTYCYCLE(750);	// angle 90 //0
		break;
	case 180 :
		M_TIMER_void_TIMER4_DUTYCYCLE(1000);	// angle 180  +90
		break;
	}
}
